name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run build
      - name: Prepare artifact
        run: |
          mkdir -p package/{dist}
          cp manifest.json package/
          cp styles.css package/ || true
          cp versions.json package/ || true
          cp -r dist package/
          cd package && zip -r ../plugin.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: plugin.zip
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.zip
